name: Build Oneplus 7 Series (Based-AOSP A16)

on:
  workflow_call:
  workflow_dispatch:

env:
  # Device env
  DEVICE_NAME : "Oneplus_7_Series"
  DEVICE_CODENAME : "RagnaR_Kernel"

  CUSTOM_CMDS : "ARCH=arm64 CC=clang CROSS_COMPILE_COMPAT=aarch64-linux-android- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- CLANG_TRIPLE=aarch64-linux-gnu- READELF=llvm-readelf LLVM_DIS=llvm-dis AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip LD=ld.lld HOSTCC=clang HOSTCXX=clang++"
  EXTRA_CMDS : "LLVM=1 LLVM_IAS=1"

  KERNEL_SOURCE : "https://github.com/beingsk5/android_kernel_oneplus_sm8150.git"
  KERNEL_BRANCH : "16.2"

  CLANG_SOURCE : "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/603a89415bbb04dff8bc577b95534479ec13fdc5/clang-r574158.tar.gz"
  CLANG_BRANCH : ""

  GCC_GNU : false
  GCC_64_SOURCE : ""
  GCC_64_BRANCH : ""
  GCC_32_SOURCE : ""
  GCC_32_BRANCH : ""

  DEFCONFIG_SOURCE: ""
  DEFCONFIG_NAME : "sm8150p_defconfig"
  DEFCONFIG_ORIGIN_IMAGE: ""
  DEFCONFIG_FROM_BOOT: false

  KERNELSU_SOURCE : ""
  KERNELSU_BRANCH : ""

  KERNELSU_AUTO_GET : "true"
  KERNELSU_AUTO_FORK : "resukisu" # magic, rsuntk , next, resukisu and sukisu
  
  SUSFS_ENABLE : true
  SUSFS_FIXED : false

  AK3_SOURCE : "https://github.com/beingsk5/AnyKernel3.git"
  AK3_BRANCH : "master"

  BOOT_SOURCE : ""

  NEED_DTBO : false
  NEED_SAFE_DTBO : false

  ROM_TEXT : "based_aosp_a16"

  # Other env
  PYTHON_VERSION: "3" # Only 2(Ubuntu 22.04 and Ubuntu 20.04) or 3(Any OS Versions).

  PACK_METHOD: "Anykernel3" # Anykernel3 need SOURCE and BRANCH, MKBOOTIMG needn't it.

  KERNELSU_METHOD: "shell" # shell, manual and only.

  PATCHES_SOURCE: "" # [your_name]/[your_patch] -> gooder123/NonGKI_Patcher
  PATCHES_BRANCH: "" # [your_branch] -> main

  SUSFS_FOLDER_FIXED: "" # Fill in your patch prefix directory here. Leave it blank if there isn't one. -> your_folder
  SUSFS_PATCH_FIXED: "" # Fill in your patches here. If there are multiple patches, please separate them with a comma. Leave it blank if there isn't one. -> patch1,patch2

  REKERNEL_ENABLE: "false" # if u need Re:Kernel.

  HOOK_METHOD: "syscall" # Manual hook method ->  syscall.
  HOOK_OLDER: "false" # contain backport older patch and syscall older patch.

  KERNEL_PATCH: "false" # If your kernel version is <= 4.9, you have the option of enabling the patch to patch the kernel_write and kernel_read functions.

  KPM_ENABLE: "true" # Anyone devices.
  KPM_INLINE: "false" # Only use it for SukiSU-Ultra.
  KPM_KPATCH_NEXT: "false" # If u want hook KPatch-Next in build step.
  KPM_PATCH_SOURCE: "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU_patch/refs/heads/main/kpm/patch_linux" # If u want to use KPM Inline,so you need set patch exec file source -> raw.githubusercontent.com/Test/Test/patch .

  BASEBAND_GUARD_ENABLE: "false" #if u want prevent unauthorized writes to critical partitions/device nodes.
  BASEBAND_GUARD_BOOT: "false" #if u want to protect boot partition.

  HIDE_STUFF: "false" # hide some of the features

  GENERATE_DTB: "false" # if u kernel need DTB , but cannot auto generate it. (Only Anykernel3).
  GENERATE_CHIP: "qcom" # only supported for qcom and mediatek.

  BUILD_DEBUGGER: "false" # Output build errors.
  SKIP_PATCH: "false" # Ignore errors found in Patch Debugger.

  BUILD_OTHER_CONFIG: "false" # Merge config files.
  MERGE_CONFIG_FILES: ""  # vendor/sm8150-perf_defconfig vendor/sm8150_defconfig

  FREE_MORE_SPACE: "false" # if u want get more space, enabled it.

jobs:
  build-kernel:
    name: Oneplus 7 Series (Based-AOSP A16)
    runs-on: ubuntu-latest # u can changed to ubuntu 22.04, and need container set ubuntu-latest
    # container: archlinux/archlinux:latest # if u need use arch linux -> archlinux/archlinux:latest or ubuntu 20.04 -> ubuntu:focal
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: ⏰ Checkout repository
        uses: actions/checkout@v4

      - name: ⌛️ Compilation environment preparation
        uses: ./.github/workflows/build-env

      - name: ⚙️ Get neccssary tools
        uses: ./.github/workflows/build-ready

      - name: 🔄 Update KernelSU-Umount
        run: |

             cd $GITHUB_WORKSPACE/device_kernel
             echo "Applying SM8150 patch"
             patch -p1 --forward --batch < sm8150.patch || true
             echo "Patch done, continuing"
       
      #      set -e
      #      cd $GITHUB_WORKSPACE/device_kernel
      #      git config user.email "actions@github.com"
      #      git config user.name "GitHub Actions"

      #     patch -p1 < sm8150.patch
            
      #     git clone --depth=1 -b power https://github.com/beingsk5/King.git power
      #     cp power/*.patch $GITHUB_WORKSPACE/device_kernel/      
      #     git am --3way --whitespace=nowarn power1.patch
      #     git am --3way --whitespace=nowarn power2.patch
      #     git am --3way --whitespace=nowarn power3.patch
      #     git am --3way --whitespace=nowarn power4.patch
      #     git am --3way --whitespace=nowarn power5.patch
      #     git am --3way --whitespace=nowarn power6.patch
      #     git am --3way --whitespace=nowarn power7.patch
      #     git am --3way --whitespace=nowarn power8.patch
      #     git am --3way --whitespace=nowarn power9.patch
      #     git am --3way --whitespace=nowarn power10.patch
      #     git am --3way --whitespace=nowarn power11.patch
      #     git am --3way --whitespace=nowarn power12.patch
      #     git am --3way --whitespace=nowarn power13.patch
      #     git am --3way --whitespace=nowarn power14.patch
      #     git am --3way --whitespace=nowarn power15.patch

      #    echo "Applying final Power patch with git apply (NOT git am)"
      #    git apply --reject --whitespace=nowarn power6.patch

      #    echo "All patches applied."

      - name: 🪝 Patch Kernel of SUSFS
        uses: ./.github/workflows/patch-susfs

      - name: 🔗 Patch for no-kprobe
        uses: ./.github/workflows/patch-no-kprobe

      - name: 🪛 Extra Kernel Options
        run: |
          # Only ${{ env.DEVICE_NAME }} use it.
          cd $GITHUB_WORKSPACE/device_kernel

          # Nothing
          # Remove SuSFS from dcache
          # sed -i '/#ifdef CONFIG_KSU_SUSFS/,/#endif/d' fs/dcache.c

      - name: 🧰 Patch Kernel of Re:Kernel
        uses: ./.github/workflows/patch-rekernel

      - name: 🔒 Patch Kernel of Baseband Guard
        uses: ./.github/workflows/patch-baseband-guard

      - name: 🚀 Build Process
        uses: ./.github/workflows/build-process

      - name: 🔩 Pack Process
        if: env.PACK_METHOD == 'Anykernel3'
        shell: bash
        run: |
                   TIME=$(date +"%Y%m%d%H%M%S")

                   cd $GITHUB_WORKSPACE/device_kernel/
                   if [[ -d "arch/arm64/configs" ]]; then
                     IMAGE_DIR="$GITHUB_WORKSPACE/device_kernel/out/arch/arm64/boot"
                   else
                     IMAGE_DIR="$GITHUB_WORKSPACE/device_kernel/out/arch/arm/boot"
                   fi

                   mkdir -p tmp
                   
                   if [[ "${{ env.AK3_SOURCE }}" =~ "osm0sis" ]]; then
                   sed -i 's/ExampleKernel by osm0sis @ xda-developers/NonGKI Kernel Build by RagnaR @ Github/g' Anykernel3/anykernel.sh
                   sed -i 's/do.devicecheck=1/do.devicecheck=0/g' Anykernel3/anykernel.sh
                   sed -i 's!BLOCK=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!BLOCK=auto;!g' Anykernel3/anykernel.sh
                   sed -i 's/IS_SLOT_DEVICE=0;/is_slot_device=auto;/g' Anykernel3/anykernel.sh
                   echo "Now using official Anykernel3."
                   else
                   echo "Now using custom Anykernel3."
                   fi
                   
                   if [[ -f "$IMAGE_DIR/Image" ]]; then
                   cp -fp $IMAGE_DIR/Image tmp
                   echo "Found Image !"
                   fi

                   mkdir -p tmp/modules/vendor/lib/modules/

                   find out/ -type f -name "*.ko" | while IFS= read -r module; do
                   filename=$(basename "$module")

                   if [ "$filename" = "wlan.ko" ]; then
                   echo "Renaming wlan.ko → qca_cld3_wlan.ko"
                   cp -v "$module" tmp/modules/vendor/lib/modules/qca_cld3_wlan.ko
                   else
                   cp -v "$module" tmp/modules/vendor/lib/modules/
                   fi
                   done

                   cp -rp ./Anykernel3/* tmp
                   cd tmp
                   7za a -mx9 tmp.zip *
                   cd ..
                   cp -fp tmp/tmp.zip ${{ env.DEVICE_CODENAME }}-${{ env.ROM_TEXT }}-$TIME-${{ env.PACK_METHOD }}.zip
                   rm -rf tmp

                   echo "PACK_NAME=${{ env.DEVICE_CODENAME }}-${{ env.ROM_TEXT }}-$TIME-${{ env.PACK_METHOD }}.zip" >> $GITHUB_ENV

      - name: ✏️ Upload Artifacts
        uses: ./.github/workflows/upload-files
